name: Sourcegraph LSIF Uploader
description: Upload LSIF data to a Sourcegraph instance
author: Sourcegraph
branding:
  icon: upload
  color: purple

inputs:
  file:
    description: The LSIF dump file to upload.
    default: dump.lsif
  root:
    description: The root of the LSIF dump
    default: ''
  endpoint:
    description: The URL of the Sourcegraph instance.
    default: https://sourcegraph.com
  github_token:
    description: Either 1. a GitHub access token with `repo` or `public_repo` scope, or 2. a GitHub installation access token (necessary when uploading to Sourcegraph.com, or any Sourcegraph instance with lsifEnforceAuth set to true).
    default: ''

runs:
  using: docker
  image: sourcegraph/src-cli:3.11.1
  args:
    - endpoint=${{ inputs.endpoint }}
    - lsif upload
    - -file=${{ inputs.file }}
    - -root=${{ inputs.root }}
    - -github-token=${{ inputs.github_token }}
